const disheList = [
    "Pudding",
    "Brownie",
    "Cookie",
    "Muffins",
    "Tea",
    "Coffee",
    "PopCorn",
    "Cheddar",
    "Cake",
    "Pie",
    "Pizza",
    "Burger",
    "Milkshake",
    "IceCream",
    "Donut",
    "Bagel",
    "Waffle",
    "Pancake",
    "Sandwich",
    "Taco",
    "Burrito",
    "Sushi",
    "Ramen",
    "Salad",
    "Soup",
];

const actionList = [
    "Monster",
    "Devourer",
    "Smasher",
    "Lawyer",
    "Zealot",
    "Leader",
    "Dealer",
    "Manager",
    "Eater",
    "Drinker",
    "Lover",
    "Hater",
    "Creator",
    "Destroyer",
    "Builder",
    "Breaker",
    "Maker",
    "Taker",
    "Giver",
    "Finder",
    "Loser",
    "Winner",
    "Champion",
    "Challenger",
    "Master",
    "Apprentice",
    "Guru",
    "Ninja",
];

export function getEnglishRandomUsername() {
    const randomDisheID = Math.floor(Math.random() * disheList.length);
    const randomActionID = Math.floor(Math.random() * actionList.length);
    return disheList[randomDisheID] + actionList[randomActionID];
}