export const endonym_to_langcode = {
    "en": "English",
    "de": "Deutsch",
    "fr": "Français",
    "pl": "Polski",
    "ja": "日本語",
    "it": "Italiano",
    "nl": "Nederlands",
    "pt": "Português",
    "es": "Español",
    "ru": "Русский",
    "sv": "Svenska",
    "zh": "中文",
    "no": "Norsk",
    "fi": "Suomi",
    "ca": "Català",
    "uk": "Українська",
    "vo": "Volapük",
    "tr": "Türkçe",
    "ro": "Română",
    "cs": "Čeština",
    "hu": "Magyar",
    "eo": "Esperanto",
    "sk": "Slovenčina",
    "da": "Dansk",
    "id": "Bahasa Indonesia",
    "he": "עברית",
    "ar": "العربية",
    "ko": "한국어",
    "lt": "Lietuvių",
    "sr": "Српски",
    "sl": "Slovenščina",
    "bg": "Български",
    "vi": "Tiếng Việt",
    "et": "Eesti",
    "ht": "Kreyòl Ayisyen",
    "hr": "Hrvatski",
    "fa": "فارسی",
    "new": "नेपाल भाषा",
    "te": "తెలుగు",
    "nn": "Norsk (Nynorsk)",
    "gl": "Galego",
    "th": "ไทย",
    "simple": "Simple English",
    "el": "Ελληνικά",
    "ceb": "Cebuano",
    "ms": "Bahasa Melayu",
    "eu": "Euskara",
    "bs": "Bosanski",
    "lb": "Lëtzebuergesch",
    "ka": "ქართული",
    "bpy": "বিষ্ণুপ্রিয়া মণিপুরী",
    "la": "Latina",
    "is": "Íslenska",
    "hi": "हिन्दी",
    "sq": "Shqip",
    "br": "Brezhoneg",
    "mr": "मराठी",
    "az": "Azərbaycanca",
    "sh": "Srpskohrvatski",
    "mk": "Македонски",
    "tl": "Filipino",
    "cy": "Cymraeg",
    "bn": "বাংলা",
    "lv": "Latviešu",
    "pms": "Piemontèis",
    "io": "Ido",
    "ta": "தமிழ்",
    "jv": "Basa Jawa",
    "oc": "Occitan",
    "su": "Basa Sunda",
    "be": "Беларуская",
    "nds": "Nedersaksies",
    "nap": "Nnapulitano",
    "scn": "Sicilianu",
    "orv": "Старая беларуская",
    "ku": "Kurdî",
    "ast": "Asturianu",
    "af": "Afrikaans",
    "wa": "Walon",
    "an": "Aragonés"
} as const;